samsarahq/api-docs

swagger.json
Refactoring the previous DispatchJobs implementation to reduce copy/paste and set up a template for defining V2 DispatchJobs. 
This closely models the structs defined in fleet_dispatch.go:
* DispatchJobV1Base => DispatchJobV1Create (with the exception of "id")
* DispatchJobV1Response => DispatchJobV1 (extends DispatchJobV1Create and adds "id", "group_id", "org_id", and "job_state")
Tested locally by using Charles to rewrite the URL in the body of samsara.com/api to point to my raw github file. Verified that the page still loads correctly.
=> Greg/swagger: Refactor DispatchJob V1 implementation

swagger.json
This PR adds support for all of the dispatch route REST endpoints in our swagger.json file. 
The routes added came from samsaradev.io/controllers/api/routes.go, with the exception of 
* /fleet/drivers/{driver_id}/dispatch/routes/{route_id}
* /fleet/vehicles/{vehicle_id}/dispatch/routes/{route_id}
For now, those will be unexported functions that only we know about, since exposing them may add unnecessary complexity.
=> swagger: Add support for dispatch routes

swagger.json
Moving driver_id and vehicle_id from the Job creation parameters to the
Route creation parameters, since we don't allow specifying driver_id and
vehicle_id on a per-job basis.
=> swagger: Remove driver_id and vehicle_id from JobCreateParam

swagger.json
Adding the `/v1/fleet/dispatch/routes/{route_id}/history` endpoint to our swagger documentation. 
Verified on editor.swagger.io that this documentation appears correctly with no validation errors.
This PR also fixes a new and unrelated validation error with the existing schema.json, which does not like references to `#/parameters/routeIdParam` or other path-based parameters. This appears to be a swagger bug in their latest schema parser.
=> Greg/swagger: Update swagger with dispatch route history fetch endpoint

swagger.json
This adds documentation for:
/v1/fleet/assets
/v1/fleet/assets/{assetId:[0-9]+}/reefer
and introduces a new "Assets" tag
Verified on http://editor.swagger.io/#
=> swagger: Add documentation for asset-specific endpoints

swagger.json
These should be startMs, not start_time. Same with endMs/end_time.
=> swagger: Update docs and fix the asset endpoint time params

swagger.json
Update existing endpoints and add new endpoint documentations to match the changes made in /backend.
1. Add `fleet/assets/locations` endpoint that shows the current locations of all assets in the group.
2. Add `engineHours` to `/fleet/assets`
3. Add `name` to the `/sensors/*` responses
4. Add `sensors/cargo` and `/sensors/door` endpoints for the cargo and door sensors.
Tested by loading the changes into http://editor.swagger.io/ and verifying the output is what we expect.
=> Add asset api docs

swagger.json
Updating swagger to include documentation for the 
* `/tags`
* `/tags/{tag_id:[0-9]+}`
endpoints. 
Tested by verifying the output at editor.swagger.io.
=> Greg/swagger: Add swagger documentation for Tag operations

swagger.json
Updating our swagger.json documentation to include the include=route query parameter for returning route information in the response payload for job_updates. 
Also fixing a JSON validation bug with an extra comma at the end of `"$ref": "#/definitions/prevJobStatus",`
=> api-docs swagger: Add include=route to job_updates endpoint

swagger.json
This change addresses Jira issue API-55; it updates the API documentation to reflect what is actually returned when calling the /fleet/drivers/summary endpoint
=> swagger: updated text of drivers/summary response

swagger.json
Updating our `/fleet/drivers/{driver_id}` endpoint to include the new `currentVehicleId` field, which indicates the vehicle ID that the driver is currently assigned to.
=> Greg/swagger: Update /fleet/drivers/{driver_id} response to include currentVehicleId

swagger.json
We're exposing scheduled departure time info as is on GET/POST
endpoints that contain dispatch job info.
Verified via http://editor.swagger.io/ that scheduled departure time info appears on the following endpoints -
```
/fleet/dispatch/routes (GET, POST)
/fleet/dispatch/routes/job_updates (GET)
/fleet/dispatch/routes/{route_id} (GET, PUT)
/fleet/dispatch/routes/{route_id}/history (GET)
/fleet/drivers/{driver_id}/dispatch/routes (GET, POST)
/fleet/vehicles/{vehicle_id}/dispatch/routes (GET, POST)
```
=> swagger: Add scheduled_departure_time_ms to DispatchJobCreate

swagger.json
Adds API docs for new GET endpoint for `/fleet/drivers/documents`
Verified in Swagger's editor.
=> swagger: Add GET /fleet/drivers/documents documentation

swagger.json
We're exposing `estimated_arrival_ms` on GET/PUT endpoints related to dispatch jobs.
This is only applicable to en-route jobs (since null responses will be automatically omitted)
This PR is related to https://github.com/samsara-dev/backend/pull/12598
Verified via http://editor.swagger.io/ that ETA info appears on the following endpoints -
```
/fleet/dispatch/routes (GET)
/fleet/dispatch/routes/job_updates (GET)
/fleet/dispatch/routes/{route_id} (GET, PUT)
/fleet/dispatch/routes/{route_id}/history (GET)
/fleet/drivers/{driver_id}/dispatch/routes (GET)
/fleet/vehicles/{vehicle_id}/dispatch/routes (GET)
```
=> swagger: Add estimated_arrival_ms to DispatchJobResponse

swagger.json
- adds endpoints for the vehicle safety score API endpoint, and then driver safety score API endpoint
- the `DriverSafetyScoreResponse` and `VehicleSafetyScoreResponse` share all the fields except the driver one will have `driverId` and vehicle will have `vehicleId`, wasn't sure if there was a way to create some structure for all the shared fields and then somehow spread them
Used https://editor.swagger.io/ to validate + test it
=> swagger: update api docs to include safety score endpoints

swagger.json
Added `vehicleId` to driver documents
Incorrectly showed driver doc API response as snake case in swagger, and corrected it here to show the response in camel case instead
=> swagger: add vehicleId to driver docs; correct snake to camel case

swagger.json
Add `actual_start_ms` and `actual_end_ms` to `DispatchRoute` and `fleet_viewer_token` to `DispatchJob`
=> swagger dispatch: actual times to route, fleet viewer token to job

swagger.json
=> swagger: add destinationAddressId to DispatchJobs

swagger.json
- adds `vehicleId` as a field on the safety score harsh event
Relevant PR: https://github.com/samsara-dev/backend/pull/14833
=> swagger: add vehicleId to safety score harsh events

swagger.json
We updated DocumentField to use `stringValue`, `numberValue`, and `photoValue` as a replacement for the generic type `value`. Only one of these values should be non-nil.
=> Update DocumentField with stringValue, numberValue, photoValue

swagger.json
Adds `destination_address_id` to our swagger docs for POST/PUT routes.
This should be merged after https://github.com/samsara-dev/backend/pull/14880 deploys.
=> Add destination_address_id to DispatchJobCreate def

swagger.json
Updating the swagger documentation to reflect the proper variable names
for vehicleId and groupId on the driver create endpoint.
Fixes INTL-327
=> go swagger: Fix snake case driver create params

swagger.json
"float" should be "number" for the type of vehicle fuelLevelPercent.
=> swagger: correct type for fuelLevelPercent

swagger.json
Modify old `startLocation` and `endLocation` fields to mean geocoded address and add new `startAddress` and `endAddress` to replace.
=> api-docs swagger: add new start and end Address field to trips 

swagger.json
This Adds `onDutyMs` and `driveMs` as response parameters to the `fleet/drivers/hos_daily_logs` endpoint.
=> Add onDutyMs and driveMs to fleet/drivers/hos_daily_logs

swagger.json
trailerId is now returned when the DVIR in question is tied to a trailer object. Updated docs to include trailerId in the example response from dvir list endpoint.
=> swagger: add trailerId to DvirListResponse definition

swagger.json
A DVIR POST endpoint matching these specs is in development. 
This POST will, for now, only allow "mechanic-style" DVIRs rather than full driver DVIRs. Users will not be able to specify specific defects that need attention, but will be able to mark a vehicle or trailer safe or unsafe. 
Marking a vehicle or trailer as safe resolves any previous unsafe DVIRs. 
A POST to this endpoint returns the newly-created DVIR.
=> swagger: API spec for dvir POST endpoint

swagger.json
Proposed changes:
1. Update driver creation payload to allow a passed in `external_id` key and value.
Example: 
```
{
...
"driver": {
"driverId": 1,
"externalIds": {
"payrollId": "123",
"externalDriverId": "123456"
}
}
}
```
2. Update all endpoints that previously routed based on `driver_id` or `vehicle_id` to now also allow the `external_id` in the following format (note that old format is still allowed as well):
Example: `GET /fleet/drivers/arcbestDriverId:123456`
Example: `GET /fleet/drivers/1`
Example: `POST /fleet/vehicles/arcbestVehicleId:ABFS18600/dispatch/routes`
Example: `POST /fleet/vehicles/1/dispatch/routes`
3. Add a patch endpoint for drivers and vehicles that allows updating a driver or vehicle based on either `driver_id`, `vehicle_id`, or `external_id`. The intension is to …
=> apidocs: add proposed external id changes for arcbest

swagger.json
Remove double curly brace typos from a few places.
=> arcbest api-docs: remove double curly typos

swagger.json
This adds documentation for `/fleet/unassigned_driving_segments`, `/fleet/unassigned_driving_segments/annotate`, and `/fleet/unassigned_driving_segments/assign`.
Tested @ http://editor.swagger.io/
=> Add documentation for unassigned segments endpoints

swagger.json
Adds documentation for newly added `/contacts/` GET endpoints. Contacts API supports 
* GET organization contacts
* GET contact by id
=> swagger: API spec for /contacts/ endpoints

swagger.json
This PR updates address api docs to include notes and contact fields in address query responses and mutation parameters.
=> swagger: updating address api docs to include notes and contacts

swagger.json
Fixing a number of issues that were discovered by the generated
ApiClient when used to test tag CRUD operations:
* Incorrect ErrorResponse payload type
* Uses GroupParam instead of GroupIdParam
* Missing parentTagId in tag object
* Missing groupId in tag object
=> go swagger.json: Fix issues with swagger definition for tags

swagger.json
This change applies to dispatch job destination addresses for POST/PUT route APIs.
[JIRA](https://samsaradev.atlassian.net/projects/ROUTE/issues/ROUTE-539)
[Spec](https://paper.dropbox.com/doc/Eng-Spec-Routes-Address-Ids--ASoN~l8e~s3Wri0HVsNfMDjPAg-xO06B35uZ5utOA4gDJmjG)
[Corresponding code change](https://github.com/samsara-dev/backend/pull/17038)
**Testing**
As seen on editor.swagger.io -
Routes POST - 
Routes PUT -
=> swagger: Mark optional fields for job destination addresses

swagger.json
Adds info about route start location address IDs, as well as when different fields associated with route start location addresses are optional.
Also updates a minor issue where we incorrectly indicated when job
destination address IDs are optional.
As seen on editor.swagger.io - 
Routes POST - 
Routes PUT -
=> api docs: Add info about route start location validation

swagger.json
Live demo for these changes: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/albert/arcbest-fleet-driver-updates/swagger.json
These doc updates are meant to reflect the changes specified in this [product spec](https://docs.google.com/document/d/1b9WG8e37rcG2P479nVNJx1D69evjSJRG-Pk9i54KnHA/edit#).
More context here and up-to-date specs for field descriptions here in the [engineering implementation spec](https://paper.dropbox.com/doc/Implementation-Spec-Driver-Settings-API-updates--ATHutWfTJT7~qla1JI2Qq77lAg-b0Y32QZTY8zTB8dCKk3hp#:h2=Use-the-new-graphql-endpoint-w).
Overall, the main change is that we want to expose more fields on the `/fleet/driver` endpoints for creating, reading, and updating driver objects.
There are three big changes:
1) …
=> Fleet Driver Settings endpoint updates

swagger.json
Live Demo: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/0aa26e4d53c4e51569f04039f3f650e45fa506c3/swagger.json#operation/patchDriverById
1) fix some indentation
2) specify `application/merge-patch+json` content type for PATCH /fleet/drivers/:id
=> Specify application/merge-patch+json content type for PATCH /fleet/drivers/:id

swagger.json
current docs: http://samsara-arcbest-api-preview-docs.s3-website-us-west-2.amazonaws.com/#operation/patchDriverById
live demo with changes: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/5b8a5736e5a2716f928420e464efbf72adb79844/swagger.json#operation/patchDriverById
We're currently requiring `id` and `name` in the message body for PATCH /fleet/drivers/id. This PR creates a new `DriverForUpdate` object in swagger that
1) removes `id` from the message body, since we're passing it in as a url param, and
2) changes the `name` field from required -> normal
The last commit to remove trailing commas is just for cleanup.
=> Fix message body for PATCH /fleet/drivers/id

swagger.json
Adds tag ID parameters to address POST and PATCH, and adds tags to responses for address single and multiple GET. 
For discussion: 
~Does it make sense to include the entire tag object in the GET responses? a ton of data comes back in the list of tags, because it's returning every entity under every tag. Would it be better to return just the list of tag IDs?~ Outcome: we'll be returning just the name & id of each tag. 
[Sandbox here.](http://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/6ea0894f5a1075a466a42596f39783d642a673a0/swagger.json#operation/AddOrganizationAddresses) If you click into the GET /addresses endpoint you can see an example tags response in context.
To be landed once this functionality is fully implemented.
=> swagger: add tags to addresses

swagger.json
Unassigned driving segments will be filtered on created time rather than real world time. The query parameters used to supply the start and end time for filtering have been updated to better describe this behavior.
[Preview](https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/dsharrison/update-unassigned-segments-query-params/swagger.json#operation/getUnassignedDrivingSegmentsByVehicleId)
=> swagger: update unassigned_driving_segments time params

swagger.json
[API-190] documentation is incorrect - for /fleet/drivers/{id}/hos_daily_logs response, the key is "days", not "summaries"
=> Correct information for /hos_daily_logs response

swagger.json
Add address object to tag single GET and tag LIST responses. 
View docs here: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/d1bf43ea37a13a68ae8f607ddf6895bdec41762b/swagger.json#operation/GetOrganizationContact
=> add addresses to tag GET endpoints

swagger.json
Add the fleet/vehicle endpoint with GET and PATCH methods.  Also adds a FleetVehicleResponse definition, since the "vehicle" returned by this endpoint differs from the existing Vehicle definition.
=> swagger: add fleet/vehicle endpoint

swagger.json
Adds docs for a `vehicle/id/stats` endpoint that returns engine state and digio (digital aux) objectStats within a timerange (no greater than 1 hour). 
https://paper.dropbox.com/doc/Mini-Dev-Spec-Pike-Electric-API-Updates--AU4cCkqxlRH7SrVwwUjOiCMVAg-wzPIvSmJf8MVofdtJXml6
Dev work on this endpoint is not complete, but Pike wanted to see an API spec.
=> swagger: add docs for vehicle/stats endpoint

swagger.json
GET for dvirs:
- corrected example data for signature fields
POST for mechanic-style dvirs:
- add required userEmail field
Preview:
https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/f760253af02565d9afe574a626924e0542cfb4b8/swagger.json
=> dvir GET & POST: add userEmail to POST and correct examples for GET

swagger.json
Adds `driveMsToday`, `onDutyMsToday`, `pendingDriveMsToday`, and `pendingOnDutyMsToday` to the `/fleet/hos_logs_summary` endpoint.
=> Add driveMsToday, onDutyMsToday, pendingDriveMsToday, and pendingOnDutyToday Ms to hos_logs_summary

swagger.json
preview link: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/1d4060fefcfdf0ae20def22621775f8206635080/swagger.json#operation/patchDriverById
jira: https://samsaradev.atlassian.net/browse/CM-423
- remove driver object in response for PUT /fleet/drivers/inactive/:id
- remove `isDeactivated` field from PATCH /fleet/drivers/:id (because we don't support modifying this field on PATCH)
- use `tagIds` in incoming requests (PATCH, POST), and return `tags` in responses (GET, PATCH, POST)
- match some driver fields to their gql variable names for consistency
- fix incorrect or missing examples
=> Update driver info api endpoints (/fleet/drivers/...)

swagger.json
Adding docs for `/fleet/drivers/{driver_id}/hos_certified_daily_log/{time_ms}`
More details and discussion of edge cases here: **https://paper.dropbox.com/doc/Arc-Best-API-Edit-Form-And-Manner--AWKkjfFAdBwu1bMWjxhY2Lq7Ag-dhVr6zVFqHZhUAmq2GBXD**
=> swagger hos_certified_daily_log: Adding shipping id & trailer number

swagger.json
All logs returned from the audit logs API include the corresponding log status for statusType regardless of whether they were created via auto duty or a manual driver status change.
=> swagger: remove the incorrect AUTO_DUTY enum from audit_logs

swagger.json
This endpoint will return the status of the log edits.
=> swagger: Add preview for /fleet/drivers/{driver_id}/log_edits

swagger.json
This change also moves unassigned drive segments to the fleet level.
=> Separate list and get responses for unassigned driving segments

swagger.json
Docs preview: https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/ehzhang/arcbest-preview-user-adjustments/swagger.json#operation/listUserRoles
For writes (POST, PATCH, PUT), using the name of a tag as a unique identifier is untenable. We should instead change this to use the tagId instead of tagName.
For role, we can actually keep using the role name (since those are effectively an enum, there's a set of specific standard roles) but we may want to introduce a custom role uuid.
From:
```
{
"name": "Jane Doe",
"email": "user@company.com",
"authType": "basic",
"organizationRole": "Read-Only Admin",
"tagRoles": [
{
"tagName": "North Carolina Distribution",
"role": "Read-Only Admin"
}
]
}
```
We've decided to settle on a payload of the shape:
```
{ …
```
=> [rfc] update tagRoles to use ids/uuids instead of the role names

swagger.json
Update to swagger docs for /fleet/unassigned_driving_segments to add filterType. Currently only filtering on createdAtMs is supported, but in the future we can add support for querying on logMs.
Renames createdAtStartMs to startMs and createdAtEndMs to endMs so the args can make sense for filterying by logMs in the future.
Also removes Default tag.
=> swagger.json: update /fleet/unassigned_driving_segments args

swagger.json
Add docs for org_wide log edits. 
[Preview](https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/samsarahq/api-docs/dsharrison/arcbest-org-wide-log-edits/swagger.json#operation/getDriverLogEdits)
=> swagger: add docs for org wide log_edits

swagger-preview.json
As we transition to kondo, the growth team is helping us setup a samsara.com/api-preview page that renders a swagger as an analog to the current samsara.com/api page. This is a initial base swagger for growth to use.
We likely do not want to have an automated pipeline setup that syncs backend kondo swagger with this one yet because we want to do staged launches as opposed to a continuous deployment of doc changes.
NOTE: we also need to clean up this description, but for now it is just acting as a dummy file to give growth something to render.
=> add base swagger kondo file for marketing to have something to render

swagger.json
Introduces ANNOTATED as a possible status for an unassigned driving segment. The ANNOTATED status represents when an unassigned driving segment has no associated driver and has been annotated.
=> Add ANNOTATED as possible status for unassigned driving segment

.github/workflows/readme-api-sync.yml
Adding the workflow_dispatch option to the Sync OAS to ReadMe workflow
so we can manually run the workflow when needed (for debugging)
=> workflows: adding the option to manually trigger github workflow

.github/workflows/readme-api-sync.yml
Add extra conditions to the readme sync workflow to happen only when
swagger-readme.json or any files under markdown directory is changed
on the master branch.
=> workflows: change condition of readme sync to happen on doc changes

scripts/readme_orderer.py
Changing the file path that the python script looks to sync markdown files.
This was changed in the backend repo to only put files in the /markdown
directory instead of creating a nested readme directory.
=> scripts: change markdown file path
