samsarahq/api-docs

- config.json
Adding the config.json file that's passed to swagger-codegen.
> api-docs: Add config.json file

- swagger.json
Fix a typo on the machine summary
> Fix /machines/history summary

- swagger.json
This change adds the asset location api to our public api.
The routes added came from samsaradev.io/controllers/api/assets.go
/fleet/asset/{assetId: [0-9]+}/location
> swagger.json: add in asset location api

- swagger.json
addressed comments from @arthurhuang here
https://github.com/samsarahq/api-docs/pull/19#pullrequestreview-98462565
1. update the endpoint to be asset/{asset_id}/locations with the plural on location
2. updated the response to be an array of location objects
> swagger.json: update to the asset locations

- swagger.json
update to match added functionality
> swagger: Add engineHours to fleet/list endpoint

- swagger.json
added information for fleet/trips startMs and endMs for window limitation.
tested and compiled with editor.swagger.io
> swagger.json: added descripton fleet/trips

- swagger.json
Testing the flow of github flow on swagger.json file
Verified the swagger.json file on editor.swagger.io
> swagger:Updated description of Assets in tags field

- swagger.json
> swagger:Updated hos_logs response to include remarks in the return body

- swagger.json
Removed a comma that was showing an error in vscode
> json swagger: removed comma that was showing an error in vscode

- swagger.json
> swagger: update api docs to include vehicle location api endpoints

- swagger.json
> swagger: Fix typo on dispatchJobId.

- swagger.json
Add the new id and timeMs properties to the DVIR list response (https://github.com/samsara-dev/backend/pull/14219).
> swagger: update dvir list

- swagger.json
> swagger.json: add api docs for addresses CRUD

- swagger.json
This is the documentation update for https://github.com/samsara-dev/backend/pull/10589 and will be merged after that change lands.
> swagger: add activeMs

- swagger.json
Change `isSafe` type bool param to a `safe` type string enum param
> swagger: update dvir POST params

- swagger.json
Changed `contactId` to `contact_id`
> swagger contacts: changing contactId to contact_id

- swagger.json
Fixing a number of swagger validation errors that show up via `swagger validate swagger.json`.
> Greg/swagger: Fix swagger validation errors

- swagger.json
Adding docs for dvir POST endpoint for mechanic-style DVIRs.
> Docs for dvir post

- swagger.json
Remove default as a category from tags, to simplify samsara.com/api documentation categories
> Remove default category from tags

- swagger.json
Update vehicle PATCH docs for arcbest commit to include patch body payload.
> api docs: add docs for vehicle patch body

- swagger.json
Updating our /fleet/list page with pagination parameters for paginating the list of devices.
> swagger.json: Add pagination params to /fleet/list

- swagger.json
Syncing the latest swagger changes for:
* New users endpoint
* Harsh accel setting names
* Reverting driver tagIds (will update backend after buildkite pipeline
is validated and re-push this change).
> swagger.json: Sync swagger changes from backend

- scripts/readme_changelog.py
Updates the changelog post formatting to handle release states and prettier titles and descriptions.
> scripts changelog: update post formatting with release states and more complete descriptions.

- scripts/readme_changelog.py
Adds logging for the changelog workflow action and corrects the environment variable name for the token.
> scripts changelog: add logging for workflow action
